def interface(game_grid):
     print("+---------+---------+---------+---------+")
     print("|         |         |         |         |")
     print("|%s|%s|%s|%s|"%(str(game_grid[0][0]).center(9),str(game_grid[0][1]).center(9),str(game_grid[0][2]).center(9),str(game_grid[0][3]).center(9)))
     print("|         |         |         |         |") 
     print("+---------+---------+---------+---------+")
     print("|         |         |         |         |") 
     print("|%s|%s|%s|%s|"%(str(game_grid[1][0]).center(9),str(game_grid[1][1]).center(9),str(game_grid[1][2]).center(9),str(game_grid[1][3]).center(9)))
     print("|         |         |         |         |") 
     print("+---------+---------+---------+---------+")
     print("|         |         |         |         |")        
     print("|%s|%s|%s|%s|"%(str(game_grid[2][0]).center(9),str(game_grid[2][1]).center(9),str(game_grid[2][2]).center(9),str(game_grid[2][3]).center(9)))
     print("|         |         |         |         |") 
     print("+---------+---------+---------+---------+")
     print("|         |         |         |         |")    
     print("|%s|%s|%s|%s|"%(str(game_grid[3][0]).center(9),str(game_grid[3][1]).center(9),str(game_grid[3][2]).center(9),str(game_grid[3][3]).center(9)))
     print("|         |         |         |         |") 
     print("+---------+---------+---------+---------+")
